name: 云编译- immortalwrt
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      source_branch:
        description: "选择源分支"
        required: false
        default: "immortalwrt-master"
        type: choice
        options:
          - immortalwrt-master
          - openwrt-main
      rootfs_partsize :
        description: "软件包分区大小（MB）"
        default: "1024"
        
    
        

env:
  PROFILE: generic
  UCI_CUSTOM_FILE: uci-custom
  PACKAGES_LIST_FILE: packages.list
  PACKAGES_FOLDER: packages
  ROOTFS_PARTSIZE: ${{ inputs.rootfs_partsize }}   # 修改软件包安装空间大小。只支持X86Reconfigure the rootfs partition size (for x86 build only), variable set in MB
  ##DOWNLOAD_URL: https://downloads.immortalwrt.org/releases/23.05.4/targets/x86/64/immortalwrt-imagebuilder-23.05.4-x86-64.Linux-x86_64.tar.xz
  ##DOWNLOAD_URL: https://downloads.immortalwrt.org/releases/24.10.0/targets/x86/64/immortalwrt-imagebuilder-24.10.0-x86-64.Linux-x86_64.tar.zst
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python3 qemu-utils genisoimage zstd

    - name: Download and extract Image Builder
      run: |
        if [[ "${{ inputs.source_branch }}" == *"immortalwrt"* ]]; then
              REPO_URL="https://downloads.immortalwrt.org/snapshots/targets/x86/64/immortalwrt-imagebuilder-x86-64.Linux-x86_64.tar.zst"
        elif [["${{ inputs.source_branch }}" == *"openwrt"*]]; then
              REPO_URL="https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-imagebuilder-x86-64.Linux-x86_64.tar.zst"
        fi
        echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV
        wget -O /tmp/imagebuilder.tar.zst $REPO_URL
        sudo tar -C /tmp -I zstd -xvf /tmp/imagebuilder.tar.zst

    - name: Set Image Builder root directory
      run: |
        ROOT_DIRECTORY=$(basename $REPO_URL .tar.zst)
        echo "ROOT_DIRECTORY=/tmp/$ROOT_DIRECTORY" >> $GITHUB_ENV

    - name: Modify .config file
      run: |
        CONFIG_FILE="$ROOT_DIRECTORY/.config"
        REPOSITORIES_CONF="$ROOT_DIRECTORY/repositories"
        # Disable iso and virtual disk image generation for x86
        sudo sed -i 's/^CONFIG_ISO_IMAGES=y/# CONFIG_ISO_IMAGES is not set/' $CONFIG_FILE
        sudo sed -i 's/^CONFIG_QCOW2_IMAGES=y/# CONFIG_QCOW2_IMAGES is not set/' $CONFIG_FILE
        sudo sed -i 's/^CONFIG_VDI_IMAGES=y/# CONFIG_VDI_IMAGES is not set/' $CONFIG_FILE
        sudo sed -i 's/^CONFIG_VMDK_IMAGES=y/# CONFIG_VMDK_IMAGES is not set/' $CONFIG_FILE
        sudo sed -i 's/^CONFIG_VHDX_IMAGES=y/# CONFIG_VHDX_IMAGES is not set/' $CONFIG_FILE
        # Reconfigure the rootfs partition size (for x86 build only)
        if [ -n "${{ env.ROOTFS_PARTSIZE }}" ] && [ "${{ env.PROFILE }}" = "generic" ]; then
          sudo sed -i 's/CONFIG_TARGET_ROOTFS_PARTSIZE=.*/CONFIG_TARGET_ROOTFS_PARTSIZE=${{ env.ROOTFS_PARTSIZE }}/g' $CONFIG_FILE
        fi
        # 配置自定义插件源
        sudo sed -i 's/^option check_signature/# option check_signature/g' $REPOSITORIES_CONF
        # #sudo sed -i '6a/src\/gz openwrt_ai https:\/\/dl.openwrt.ai\/releases\/24.10\/packages\/x86_64\/kiddin9\/' $REPOSITORIES_CONF
        sudo sed -i '6a\src/gz openwrt_ai https://dl.openwrt.ai/releases/24.10/packages/x86_64/kiddin9' $REPOSITORIES_CONF
    - name: Copy files
      run: |
        # Creator folders
        sudo mkdir -p $ROOT_DIRECTORY/files/etc/uci-defaults
        sudo mkdir -p $ROOT_DIRECTORY/packages
        # Copy custom setting file
        sudo cp $UCI_CUSTOM_FILE $ROOT_DIRECTORY/files/etc/uci-defaults
        # Copy packages list
        sudo cp $PACKAGES_LIST_FILE $ROOT_DIRECTORY/files/packages.list
        # Copy ipk files
        sudo cp $PACKAGES_FOLDER/*.ipk $ROOT_DIRECTORY/packages

    - name: Compile firmware
      run: |
        cd $ROOT_DIRECTORY
        PACKAGES=$(cat $ROOT_DIRECTORY/files/packages.list | tr '\n' ' ')
        sudo make image PROFILE="$PROFILE" PACKAGES="$PACKAGES" FILES="files"
        echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        # Organize files
        sudo mkdir -p /tmp/bin_firmware
        sudo find bin -type f -exec sudo cp {} /tmp/bin_firmware/ \;

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: ImmortalWrt-firmware-${{ env.PROFILE }}-${{ env.FILE_DATE }}
        path: /tmp/bin_firmware

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
